---
title: "Assessment tree"
author: "Klinkenberg"
date: "4/6/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("collapsibleTree")
# install.packages("data.tree")
library("collapsibleTree")
library("readxl")
library("data.tree")
```

Assessment decision tree for tool selection based on answer types. Select the item type you want to use and find out what kind of assessment application to use.

```{r, echo=FALSE}
assessment.tree <- read_excel("assessment_tree.xlsx")

# use data tree

assessment.tree$pathString <- paste("Question Type", 
                                    assessment.tree$question.type, 
                                    assessment.tree$question.options,
                                    assessment.tree$application,
                                    sep = "/")

# Get rid of NA/

assessment.tree$pathString <- gsub("NA/", "", assessment.tree$pathString)

at <- as.Node(assessment.tree)
print(at, "question.type", "question.options", "application", limit = 20)

at <- as.data.frame(at)

collapsibleTree(
  # assessment.tree,
  at,
  root = "Question Type",
  hierarchy = c("question.type", "question.options", "application"),
  width = 800
)
```

